baseURL = 'https://amlucas0xff.github.io/blog/'
languageCode = 'en-us'
title = 'Blog Hero'
defaultContentLanguage = "en"
hasCJKLanguage = false

[pagination]
pagerSize = 5

[params]
  description = "A cybersecurity specialist exploring tech and homelabs"

[module]
  [[module.imports]]
    path = "github.com/CaiJimmy/hugo-theme-stack/v3"
  
  [[module.mounts]]
    source = "/home/amlucas/Documents/obsidian/blog/posts"
    target = "content/posts"
