baseURL = 'https://amlucas0xff.github.io/blog/'
languageCode = 'en-us'
title = 'Blog Hero'

[params]
  description = "A cybersecurity specialist exploring tech and homelabs"
  avatar = "/blog/images/avatar.png"
  
  [params.author]
    name = "Alexandre Lucas (amlucas0xff)"
    image = "/blog/images/avatar.png"

[module]
  [[module.imports]]
    path = "github.com/hugo-sid/hugo-blog-awesome"
  
  [[module.mounts]]
    source = "/tmp/obsidian-vault/blog"
    target = "content"
