baseURL = 'https://amlucas0xff.github.io/blog/'
languageCode = 'en-us'
title = 'Blog Hero'
defaultContentLanguage = "en"
hasCJKLanguage = false

[pagination]
pagerSize = 5

[params]
  description = "A cybersecurity specialist exploring tech and homelabs"

# Module configuration moved to config/_default/module.toml
# to maintain consistency with theme configuration
